services:
  db:
    image: postgres:13
    container_name: odoo-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:16.0
    container_name: odoo-web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - MOVIE_API_URL=${MOVIE_API_URL}
      - MOVIE_API_KEY=${MOVIE_API_KEY}
    volumes:
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    #command: >
    #  bash -c "odoo -d odoo -i base --without-demo=all --stop-after-init && odoo -c /etc/odoo/odoo.conf"
    command: >
      bash -c "
       
        odoo -d odoo -i base,movie_manager --without-demo=all --stop-after-init &&
        odoo -c /etc/odoo/odoo.conf"
# envsubst < /mnt/extra-addons/movie_manager/data/config_parameters.template.xml > /mnt/extra-addons/movie_manager/data/config_parameters.xml &&
volumes:
  odoo-db-data:
